### ISSUE TITLE
Better syntax highlighing for Bash

### ISSUE THREAD

**Issue by Crilum** [Thertzlor/semantic-rainbow#1]
Just installed your theme in VS Code, and opened my Bash code, and it looks cool, but doesn't look, well, very rainbowy:
![image](https://user-images.githubusercontent.com/91354257/147785823-b87b87ce-284b-4f30-bfe6-bf642d15a394.png)

If Bash has Semantic Highlighting, maybe you could add some syntax highlighting for it? :smiley:

**Comment by Thertzlor** [comment]
Bash has, so far, no semantic highlighting. It's also never going to be the most colorful of languages since there just aren't that many different constructs.

And just to reiterate the theme does not provide grammars, it just colors tokens and grammar information that is already provided. For Bash a good provider seems to be [Bash IDE](https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode)

From there I tweaked a few settings and for some more accurate colorings for commands, variables and assignments, parameters and modifiers:
![image](https://user-images.githubusercontent.com/72997728/155861421-c5536b87-1d4a-4a32-985c-289e1bf8d158.png)

These changes are included in the new 1.0.5 release.

**Comment by Crilum** [comment]
Thanks!
