### ISSUE TITLE
Disable italics?

### ISSUE THREAD

**Issue by GollyJer** [Thertzlor/semantic-rainbow#4]
Hey! I found this theme the other day and actually love it. Thanks!

I'm curious why "Any time any value is declared or initialized, the token will be displayed in italics."
Is there a way to disable this in settings.json?

Thanks again!

**Comment by Thertzlor** [comment]
Hello,

Rendering initializations in italics was done because I wanted to set them apart visually from normal references without "using up" another color.
With most fonts I use the italic effect is also fairly subtle, but I have seen fonts where italics are these crazy cursive monstrosities  so I can understand that in those cases it would be annoying.

Unfortunately VSCode does not offer a quick option to disable italics. You could attempt to [override the styles](https://github.com/microsoft/vscode/issues/32579#issuecomment-341502559) manually but as Semantic Rainbow introduces ridiculously many and very specific styles this will likely not catch everything.

The best way to get rid of cursive is to generate a variation of the theme that does not include cursive tokens to begin with, by changing the formatter settings in the config.json:
<img width="293" alt="image" src="https://github.com/Thertzlor/semantic-rainbow/assets/72997728/41a2a7c8-bfda-447c-b3fa-4e238dabc34e">
This is how the cursive declarations are implemented right now, leaving it out removes them entirely.

Anyway, you are in luck as I was working on new features that deal with making theme variations easier to define. A non-italic version of a theme seems like a good example to demonstrate those features, so I went ahead and included one in the latest release.
The regular theme is unchanged but you can now select the **Semantic Rainbow - No Italics** theme after updating the extension.

**Comment by GollyJer** [comment]
Sweet! Thank you!
